server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 핵심 : 모든 요청을 index.html로 보내서 리액트 라우터가 처리하도록
        try_files $uri $uri/ /index.html;
    }

    # Vite 개발 환경에서 설정했던 Aladin API 프록시를 Nginx에서도 설정
    location /aladin-api/ {
        proxy_pass http://www.aladin.co.kr/;
        proxy_set_header Host www.aladin.co.kr;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 에러 페이지 설정 (선택 사항)
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
