-- 1. Users 테이블
-- Supabase에서는 보통 UUID를 유저 식별자로 많이 사용합니다.
CREATE TABLE public."Users" (
  user_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  pw TEXT NOT NULL,
  nickname TEXT NOT NULL
);

-- 2. Books 테이블 
-- MyLibrary와 Reviews에서 이 테이블을 참조(FK)해야 하므로 먼저 생성합니다.
CREATE TABLE public."Books" (
  book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT,
  description TEXT,
  publisher TEXT,
  img TEXT,
  genre TEXT,
  mylibrary_id BIGINT, 
  total_pages INTEGER
);

-- 3. Visits 테이블
CREATE TABLE public."Visits" (
  visit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public."Users"(user_id) ON DELETE CASCADE,
  last_login TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  count INTEGER DEFAULT 1
);

-- 4. MyLibrary 테이블
CREATE TABLE public."MyLibrary" (
  mylibrary_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public."Users"(user_id) ON DELETE CASCADE,
  book_id BIGINT REFERENCES public."Books"(book_id) ON DELETE CASCADE,
  status TEXT, -- 예: '읽는 중', '읽을 책', '읽은 책'
  start_date TIMESTAMP WITH TIME ZONE,
  end_date TIMESTAMP WITH TIME ZONE,
  current_page INTEGER DEFAULT 0
);

-- 5. Reviews 테이블
CREATE TABLE public."Reviews" (
  review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public."Users"(user_id) ON DELETE CASCADE,
  book_id BIGINT REFERENCES public."Books"(book_id) ON DELETE CASCADE,
  description TEXT,
  star INTEGER CHECK (star >= 1 AND star <= 5), -- 별점은 1~5 점만
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() -- 나중에 "최신 리뷰(review_id 큰 순)" 정렬에 사용할 생성 날짜
);

-- 6. Likes (리뷰 좋아요) 테이블
CREATE TABLE public."Likes" (
  like_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id BIGINT REFERENCES public."Reviews"(review_id) ON DELETE CASCADE,
  user_id UUID REFERENCES public."Users"(user_id) ON DELETE CASCADE,
  UNIQUE(review_id, user_id) -- 한 유저가 같은 리뷰에 중복으로 좋아요를 누르지 못하게 막음
);

-- 7. Goal_of_month 테이블
CREATE TABLE public."Goal_of_month" (
  goal_month_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public."Users"(user_id) ON DELETE CASCADE,
  goal INTEGER,
  month TEXT -- 예: '2026-03' 등 문자열로 월 저장
);

-- 8. Goal_of_year 테이블
CREATE TABLE public."Goal_of_year" (
  goal_year_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public."Users"(user_id) ON DELETE CASCADE,
  goal INTEGER,
  year INTEGER -- 예: 2026
);

-- 9. Follows 테이블
CREATE TABLE public."Follows" (
  follow_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  following_user UUID REFERENCES public."Users"(user_id) ON DELETE CASCADE,
  followed_user UUID REFERENCES public."Users"(user_id) ON DELETE CASCADE,
  UNIQUE(following_user, followed_user) -- 중복 팔로우가 안 되도록 설정
);
